port: "8080"

postgresql_db:
  username: "postgres"
  host: "localhost"
  port: "5436"
  dbname: "postgres"
  sslmode: "disable"

redis_db:
  port: "6380"

amazon_db:
  region: "eu-north-1"
  access-key: 
  secret-access-key: 
