port: "8000"

postgresql_db:
  username: "postgres"
  host: "localhost"
  port: "5436"
  dbname: "postgres"
  sslmode: "disable"

redis_db:
  port: "6380"

amazon_db:
  region: "eu-north-1"
  access-key: "AKIA3FLDY237XQZJCDV5"
  secret-access-key: "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"